### ISSUE TITLE
What is ' '' in the dataset?

### ISSUE THREAD

**Issue by guotong1988** [google-research-datasets/wiki-split#2]
![image](https://user-images.githubusercontent.com/4702353/49134140-807bd380-f31d-11e8-8f71-40f0afeb28d9.png)

**Comment by conorg000** [comment]
Hi @guotong1988 these look like accidental apostrophes that occur in Wikipedia. It usually happens when an article contains a quote and the quote finishes with a word surrounded by apostrophes. Since the full stop appears before the quotation marks and the apostrophe, they carry over on to the next sentence. The finishing apostrophe and closing quotation marks look like they are part of the following sentence, which is why some of the data starts with unnecessary punctuation marks.
Example (line 13 of train.tsv): 
**' "Joseph Barboza later revealed the location...**
In the actual Wikipedia article, the sentence before this one is a quote, finishing with a colloquial term.
**"I told him that... he didn't trust 'the Pig.''' Joseph Barboza later revealed the location...**
So the three punctuation marks have made it into the next sentence. Hope that helps!

**Comment by guotong1988** [comment]
Thank you!
